SON-1984: es9618xx: fix watchdogutil failure in fast-reboot script
Fix failure of watchdogutil in the fast-reboot script. This failure occurs
because watchdogutil uses the sonic_platform's chassis.py, which in turn
instantiates the sonic_platform's thermal module that attempts to connect
to the Redis DB after it has been closed.
Failure log:
Traceback (most recent call last):
  File "/usr/local/bin/watchdogutil", line 8, in <module>
    sys.exit(watchdogutil())
  .
  .
  .
  File "/usr/local/lib/python3.9/dist-packages/sonic_platform/platform.py", line 21, in __init__
    self._chassis = Chassis()
  File "/usr/local/lib/python3.9/dist-packages/sonic_platform/chassis.py", line 48, in __init__
    self.__initialize_fan()
  File "/usr/local/lib/python3.9/dist-packages/sonic_platform/chassis.py", line 63, in __initialize_fan
    from sonic_platform.fan_drawer import FanDrawer
  File "/usr/local/lib/python3.9/dist-packages/sonic_platform/fan_drawer.py", line 12, in <module>
    from sonic_platform.fan import Fan
  File "/usr/local/lib/python3.9/dist-packages/sonic_platform/fan.py", line 13, in <module>
    from .thermal import logger
  File "/usr/local/lib/python3.9/dist-packages/sonic_platform/thermal.py", line 25, in <module>
    class Thermal(ThermalBase):
  File "/usr/local/lib/python3.9/dist-packages/sonic_platform/thermal.py", line 37, in Thermal
    Thermals_db.connect(Thermals_db.STATE_DB)
  File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1909, in connect
    return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
RuntimeError: Unable to connect to redis: Cannot assign requested address

Signed-off-by: Asher Oved <ashero@xsightlabs.com>