XSW-10893: es9618xx: fix temperature reading for transceivers without vdm support
Fix bug in reading transceiver bulk status via the `get_transceiver_bulk_status`
API for transceivers that do not support VDM (Versatile Diagnostics Monitoring).
The issue occurred when accessing `VDM_REAL_VALUE` in `get_transceiver_bulk_status`
without verifying that VDM is supported by the transceiver.

This bug caused the following warning and error for example:
sonic WARNING pmon#thermalctld: Failed to update thermal status for OSFP 1 - AttributeError("'NoneType' object has no attribute 'VDM_REAL_VALUE'")
sonic ERR pmon#thermalctld: Failure in XCVR temperature evaluation: 'NoneType' object has no attribute 'VDM_REAL_VALUE'

The issue is resolved by calling `get_module_temperature` directly instead
of the `get_transceiver_bulk_status` API.

Signed-off-by: Asher Oved <ashero@xsightlabs.com>