SON-1984: es9618xx: fast-reboot_plugin: fix interfaces oper state after runing fast-reboot
Add fast-reboot_plugin script to perform XPCI module unloading and chip reset, as required
in clause 6 of https://github.com/sonic-net/SONiC/wiki/Fast-Reboot#implementation-details.
Without this script, the interfaces oper state remained 'down' instead of 'up' after
performing a fast reboot, as shown by the `show interfaces description` command.

The addition of the fast-reboot_plugin script resolved the failure of sonic-mgmt's fast-reboot
community test by setting the interfaces oper state to `up`. This prevented the test from failing
due to a timeout while waiting for the interfaces oper state to become `up`.

The failure message from sonic-mgmt's fast-reboot community test was:
AssertionError: Not all transceivers are detected or interfaces are up in 300 seconds

Signed-off-by: Asher Oved <ashero@xsightlabs.com>